apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: registry.cn-qingdao.aliyuncs.com/zhangkai8048/carina
    context: .
    docker:
      dockerfile: Dockerfile  
  local:
    push: true        

deploy:
  helm:
    releases:
      - name: test-carina
        chartPath: ./charts
        setValues:
          image.carina.repository: registry.cn-qingdao.aliyuncs.com/zhangkai8048/carina
          image.carina.tag: v0.9.1-78-g8c1cbf7-dirty
          image.carina.pullPolicy: IfNotPresent
          carina-scheduler.enabled: true
          carina-scheduler.image.repository: registry.cn-qingdao.aliyuncs.com/zhangkai8048/scheduler
          carina-scheduler.image.tag: v0.9.1-72-g15624df
          carina-scheduler.image.pullPolicy: IfNotPresent
        imageStrategy:
          helm: 
           explicitRegistry: true
  