apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: registry.cn-qingdao.aliyuncs.com/zhangkai8048/carina
    context: .
    docker:
      dockerfile: Dockerfile    

deploy:
  helm:
    releases:
      - name: test-csi
        chartPath: ./charts
        setValues:
          image.carina.repository: registry.cn-hangzhou.aliyuncs.com/antmoveh/carina
          image.carina.tag: v0.9.0-46-g5d042b1-dirty
          image.carina.pullPolicy: Always
        imageStrategy:
          helm: 
           explicitRegistry: true
