---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-csi-config
  namespace: {{ .Release.Namespace }}
{{ include "carina-node.labels" . | indent 2 }}
data:
 config.json: |-
    {
      "diskSelector": [
        {
          "name": "hdd1" ,
          "re": ["vdb"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "hdd2", 
          "re": ["vdc"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
        {
          "name": "ssd1",
          "re": ["loop*","vdd1"],
          "policy": "RAW",
         "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "ssd2",
          "re": ["vdd2"],
          "policy": "RAW",
          "nodeLabel": "kubernetes.io/hostname"
        }
      ],
      "diskScanInterval": "300",
      "schedulerStrategy": "spreadout"    
    }
