---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-carina-raw
  namespace: {{ .Release.Namespace }}
provisioner: carina.storage.io
parameters:
  # file system
  csi.storage.k8s.io/fstype: {{ .Values.storage.fstype }}
  # disk group
  carina.storage.io/disk-type: "carina-raw-ssd"
  carina.storage.io/exclusivity-disk: "false" 
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
allowVolumeExpansion: true
# WaitForFirstConsumer表示被容器绑定调度后再创建pv
volumeBindingMode: WaitForFirstConsumer
mountOptions: