---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-csi-config
  namespace: {{ .Release.Namespace }}

data:
 config.json: |-
    {
      "diskSelector": [
         {
          "name": "carina-vg-ssd" ,
          "re": ["vdb"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "carina-vg-hdd" ,
          "re": ["vdc"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "carina-vg-test-ssd" ,
          "re": ["vdd"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
        {
          "name": "carina-vg-test-vdd" ,
          "re": ["vdd1"],
          "policy": "LVM",
          "nodeLabel": "topology.carina.storage.io/vgs"
        },
         {
          "name": "vdd1" ,
          "re": ["loop*"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "vdd2" ,
          "re": ["a"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "hdd1" ,
          "re": ["a"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "hdd2" ,
          "re": ["a"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "carina-vg-test-raw",
          "re": ["loop*"],
          "policy": "RAW",
          "nodeLabel": "kubernetes.io/hostname"
        }
      ],
      "diskScanInterval": "300",
      "schedulerStrategy": "spreadout"    
    }
