# permissions for end users to view nodedevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodedevice-viewer-role
rules:
- apiGroups:
  - carina.storage.io
  resources:
  - nodedevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - carina.storage.io
  resources:
  - nodedevices/status
  verbs:
  - get
