# permissions for end users to edit nodedevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodedevice-editor-role
rules:
- apiGroups:
  - carina.storage.io
  resources:
  - nodedevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - carina.storage.io
  resources:
  - nodedevices/status
  verbs:
  - get
