apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: registry.cn-hangzhou.aliyuncs.com/antmoveh/scheduler
    context: .
    docker:
      dockerfile: Dockerfile 
           

deploy:
  helm:
    releases:
      - name: test-sheduler
        chartPath: ./charts
        setValues:
          image.repository: registry.cn-hangzhou.aliyuncs.com/antmoveh/scheduler
          image.tag: v0.9.0-73-g97f88fc-dirty
          image.pullPolicy: Always
        imageStrategy:
          helm: 
           explicitRegistry: true
