apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: registry.cn-qingdao.aliyuncs.com/zhangkai8048/scheduler
    context: .
    docker:
      dockerfile: Dockerfile 
  tagPolicy:
    dateTime:   #image tag 
      format: "2006-01-02-15-04-05"
      timezone: "Local"   
  local:
    push: true    
           

deploy:
  helm:
    releases:
      - name: test-sheduler
        chartPath: ./charts
        setValues:
          image.repository: registry.cn-qingdao.aliyuncs.com/zhangkai8048/scheduler
          image.tag: 2022-03-27-09-08-44
          image.pullPolicy: Always
        imageStrategy:
          helm: 
           explicitRegistry: true
