---
apiVersion: v1
kind: ConfigMap
metadata:
  name: carina-csi-config
  namespace: kube-system
  labels:
    class: carina
data:
  config.json: |-
    {
      "diskSelector": [
        {
          "name": "hdd1" ,
          "re": ["loop*"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "hdd2",
          "re": ["loop*", "ad*"],
          "policy": "LVM",
          "nodeLabel": "kubernetes.io/hostname"
        },
        {
          "name": "ssd",
          "re": ["loop*", "vd*"],
          "policy": "RAW",
         "nodeLabel": "kubernetes.io/hostname"
        },
         {
          "name": "ssd",
          "re": ["loop*", "vd*"],
          "policy": "RAW",
          "nodeLabel": "kubernetes.io/hostname"
        }
      ],
      "diskScanInterval": "300",
      "schedulerStrategy": "spreadout"
    }