---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-carina-raw
  namespace: carina
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-carina-raw
  volumeMode: Filesystem